### ISSUE TITLE
Discrepancies between List Sequence diagram and code

### ISSUE THREAD

**Issue by OVReader** [AY2223S1-CS2113-F11-1/tp#141]
Here are some of the discrepancies:
1. `ui` and `clientlist` objects are not deleted at any point when the program is running
2. Convention-wise for sequence diagram, when a object is deleted (annotated by the red `X`), the lifeline should not continue to extend and thus, there should not be any second object below the red `X`.

**Comment by zoranabc201** [comment]
1. Noted
2. This is what sequence diagrams on plantuml look like. They show objects in the bottom.
[https://plantuml.com/sequence-diagram](https://plantuml.com/sequence-diagram)
