### ISSUE TITLE
[PE-D][Tester A] UG clarity

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2113-F11-1/tp#146]
Can include an expected output for all commands ie. property add as it was a bit confusing

![image.png](https://raw.githubusercontent.com/Franky4566/ped/main/files/3510595f-3621-4503-a5b3-a5ed36c4060a.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: Franky4566/ped#1

**Comment by zoranabc201** [comment]
Solved for my part.

**Comment by OVReader** [comment]
Issue resolved
