### ISSUE TITLE
[PE-D][Tester E] Add property feature allows two different properties to exist at the same postal code

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2113-F11-1/tp#147]
Two different street names can exist at the same postal code, which should not be allowed
![Screenshot 2022-10-28 at 4.50.25 PM.png](https://raw.githubusercontent.com/jorellesee/ped/main/files/3a2efc00-bb76-4732-b18f-63d7e2693238.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: jorellesee/ped#2

**Comment by OVReader** [comment]
HI, thank you for the review.
First, it is entirely ok for properties to have the same postal code. (Title a bit misleading)
For example, `18 College Ave East #01-01, Singapore 138593` and `18 College Ave East #01-02, Singapore 138593` are completely different properties but can have the same postal code.

However, I do agree that having different street names for the same postal code is illogical but at this iteration there is no plan for such form of validation to be implemented as it is impossible to achieve without any external API that checks against entire Singapore address database. Without the API,  it is impossible to determine which of the conflicting street name is the correct one.

Hence, I shall put a disclaimer in the user guide later.
