### ISSUE TITLE
[PE-D][Tester E] App should tell me that no property was found 

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2113-F11-1/tp#151]
App should tell me that no property was found but instead, tells me a list of things I can do
![Screenshot 2022-10-28 at 4.55.28 PM.png](https://raw.githubusercontent.com/jorellesee/ped/main/files/9da508a1-c9d8-4577-b47f-04c0416c395c.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: jorellesee/ped#4

**Comment by zoranabc201** [comment]
If you enter an incorrect command you get told that you entered an incorrect command. .
It works as intended if you actually entered the correct command.
