### ISSUE TITLE
[PE-D][Tester C] Testing Overview

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2113-F11-1/tp#168]
# handled error
- double space for address
- no unit number
- non 6 digit postal code
- other price 
- random type

- non SG phone 
- non int budget
- add trailing spaces in between

- pair:
	- non int index
	- out of bound index
	- pair the same pair again

- storage
	- delete a paired address or client will automatically delete the pairing (handled well)
	- wrong format will not be added (handled well)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: Than-Duc-Huy/ped#3

**Comment by wilsonngja** [comment]
Thanks for giving an overview of the areas you tested for the bugs. We really appreciate the effort in helping us reduce the bug count.
