### ISSUE TITLE
[PE-D][Tester C] Quality of Life Recommendation

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2113-F11-1/tp#169]
- The flags have to come in order
- command "find" when there is prefix whitespace (but i think it is expected)
- A help command would be appreciated

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: Than-Duc-Huy/ped#4

**Comment by wilsonngja** [comment]
Thanks for the feedback. With regards to the find, the whitespace will be trimmed. 
A help command has also been integrated into the program with #229
