### ISSUE TITLE
[PE-D][Tester B] User could bypass the duplication of address by selecting different house types

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2113-F11-1/tp#178]
A property in Singapore could hardly have more than one type. However, user can bypass the "no duplication of address" functionality by inputting different type of housing. 

![Screenshot 2022-10-28 at 18.11.10.png](https://raw.githubusercontent.com/HT-T/ped/main/files/733205f0-3a5d-4d9f-a498-ee95e9a95d0f.png)

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: HT-T/ped#5

**Comment by OVReader** [comment]
HI, thank you for the review.
The definition of duplication of address means having addresses with the exact same detail (case insensitive).
For example, `18 College Ave East #01-01, Singapore 138593`  and  `18 College Ave East #01-02, Singapore 138593` are completely different addresses.
Hence, the same should apply to `18 College Ave East, Singapore 138593` as well.

Of course, having the same street name for different address format is still illogical but at this iteration there is no plan to implement such form of validation as it is impossible to achieve without any external API that checks against entire Singapore address database.

Hence, I shall put a disclaimer in the user guide later.
