### ISSUE TITLE
Incomplete DeveloperGuide.md

### ISSUE THREAD

**Issue by wilsonngja** [AY2223S1-CS2113-F11-1/tp#226]
The Developer Guide is currently incomplete and requires addition of the following portion:

- Product Scope  (@ngdeqi)
- User Stories (@ngdeqi)
- Non Functional Requirements (@wilsonngja)
- Glossary (@OVReader)
- Instructions for Manual Testing (@wilsonngja, @zoranabc201, @ngdeqi, @FeliciaBeatrice, @OVReader)

**Comment by OVReader** [comment]
Related to #268 (Instructions for Manual Testing for Add)
Related to #270 (Glossary)

**Comment by OVReader** [comment]
DG completed
